# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField()),
                ('session_id', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('maquina', models.CharField(max_length=100)),
                ('objetos', models.TextField()),
                ('processo', models.CharField(max_length=100)),
                ('locks', models.IntegerField(default=1)),
                ('killed_in', models.DateTimeField(auto_now_add=True)),
                ('killed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
